### PR TITLE
RELATED: RAIL-3962 Upgrade GoodData.UI to version 8.9.0

### PR DESCRIPTION
**Pull request by no23reason**
JIRA: RAIL-3962

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by plavemar — APPROVED** [review]
LGTM

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-fossa-scanning-zuul-el7/29/ : FAILURE in 15m 04s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-merge-compliance-check/30/ : SUCCESS in 21s

**Pull request merged**
