### PR TITLE
FET-711, RAIL-2775 add SDK upgrade script, upgrade SDK to 8.3.0

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by lupko — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-fossa-scanning-zuul-el7/16/ : FAILURE in 12m 43s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-merge-compliance-check/17/ : SUCCESS in 22s

**Pull request merged**
