### PR TITLE
FEATURE: MKB-3182 Add DashboardView example

### PR DESCRIPTION
**Pull request by BugsBunny338**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by pbenes — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-fossa-scanning-zuul-el7/22/ : FAILURE in 4m 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-merge-compliance-check/23/ : SUCCESS in 24s

**Pull request merged**
