### PR TITLE
FEATURE: MKB-1685 Improve Headline example

### PR DESCRIPTION
**Pull request by BugsBunny338**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by koles — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-fossa-scanning-zuul-el7/7/ : SUCCESS in 10s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-merge-compliance-check/8/ : SUCCESS in 14s

**Pull request merged**
