### PR TITLE
RELATED: RAIL-4600 update sdk to 8.12.0

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-merge-compliance-check/34/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-examples-fossa-scanning-zuul/1/ : FAILURE in 13m 54s (non-voting)

**Pull request merged**
